# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3dcf3333-7594-4b49-a1d2-7e623963a7b6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3dcf3333-7594-4b49-a1d2-7e623963a7b6".device = "/dev/disk/by-uuid/3dcf3333-7594-4b49-a1d2-7e623963a7b6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8392-B9B5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d8080bd5-3a31-493f-b81d-fa33e238473d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
